### ISSUE TITLE
RGB input

### ISSUE THREAD

**Issue by I3aer** [Kirstihly/Edge-Directed_Interpolation#1]
Could you tell me how you pass 3 channel RGB image as argument ? Your code cannot take RGB image as input as
 try:
        w, h = img.shape
except:
        sys.exit("Error input: Please input a valid grayscale image!")

**Comment by Kirstihly** [comment]
Yes, as stated the input image should be in grayscale. You can try producing RGB images one channel at a time and then stack 3 channels together.
